;1) DEFINE AN ARRAY AND INCREASE EACH ELEMENT BY ONE   

;DECLARING AN UNINITIALISED ARRAY
ORG 100H;  
MOV BX, 6000H;
MOV DS, BX;             DUE TO AUTOMATIC INTIALISATION DS AND BX START FROM THE SAME LOCATION HENCE INITIALISE IT MANUALLY
;WHEN WE TRANSFER THE DATA THE MNEMONICS OF THE DATA WILL BE CHANGED HENCE RANDOM

PRICES DB 40              ; RANK-> NAME OF ARRAY; DB->DATA OF BYTES ; 40 IS SIZE OF ARRAY

MOV BX, OFFSET PRICES;
MOV CX, 40; 
MOV AL, 10;

L1:MOV [BX], AL;
ADD AL, 10;
INC BX;    
LOOP L1;

MOV CX, 40;

L2 : MOV AL,[BX];  
INC AL;
MOV [BX], AL;
INC BX;
LOOP L2;






;DECLARING INITIALISED ARRAY
;RANK DB 01H.02H,03H,04H,05H;        ARRAY OF 5 ELEMENTS WITH VALUES A[0]=01, A[1]=02, AND SO ON..
